
name: SSH Connection

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Connect to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: giganigga
          script: |
            cd apps/
            rm -r iptv-server
            git config user.name "GitHub Actions"
            git config user.email "<>"
            git clone https://markulT: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@github.com/markulT/iptv-server.git
            cd iptv-server/
            git config --local credential.helper store
            git config --local credential.https://github.com.username ${{ secrets.GITHUB_TOKEN }}
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            sudo ln -s "$NVM_DIR/versions/node/v16.10.0/bin/pm2" "/usr/local/bin/pm2"
            npm i
            npm run build
            pm2 delete strapi
            NODE_ENV=production PRIVATE_API_KEY_MAILGUN=${{ secrets.PRIVATE_API_KEY_MAILGUN }} MAILGUN_SENDING_DOMAIN=${{ secrets.MAILGUN_SENDING_DOMAIN }} REDIRECT_LINK=${{ secrets.REDIRECT_LINK }} pm2 start npm --name strapi -- run start:prod
            pm2 status